cutoff: 25
job_name: job_2023-09-12_id-429088_test_v000
n_iterations: 1
n_query: 3
nu: 0.5
reason: test new submit.sh file
scoring: r2
ylog: false

commit_hash: "23366cf"
date: "Tue Sep 12 15:16:53 UTC 2023"
