name: active-learning
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3
  - snakemake
  - jupytext
  - papermill
  - notebook
  - dask
  - dask-ml
  - scikit-learn
  - tqdm
  - ipywidgets
  - pip:
    - git+https://github.com/wd15/pymks@flakes
