cutoff: 20
job_name: job_2023-09-12_id-429124_nu-1_0_r2_cutoff-20_v001
n_iterations: 20
n_query: 400
nu: 1.0
reason: run with nu=1.0 and cutoff of 20
scoring: r2
ylog: false

commit_hash: "2a88c9d"
date: "Tue Sep 12 21:06:53 UTC 2023"
