n_iterations: 80
scoring: "r2"
n_query: 200
job_name: "job_2023-08-31_v000_r2"
reason: "run with r2 just to check the results"
nu: 0.5
ylog: false
commit_hash: "80155a0"
date: "Thu Aug 31 12:13:18 EDT 2023"
