cutoff: 25
job_name: job_2023-08-31_test-run-with-hao_v000
n_iterations: 1
n_query: 10
nu: 0.5
reason: testing with hao
scoring: r2
ylog: false

commit_hash: "e77626c"
date: "Wed Sep 13 03:51:24 PM EDT 2023"
