cutoff: 20
job_name: job_2023-10-12_query-800_v000
n_iterations: 20
n_query: 800
nu: 1.5
reason: 800 queries
scoring: mae
slurm_id: 441224
ylog: 'true'

commit_hash: "088a97b"
date: "Mon Oct 30 16:36:22 UTC 2023"
