cutoff: 20
job_name: job_2023-10-12_query-1600_v000
n_iterations: 20
n_query: 1600
nu: 1.5
reason: 800 queries
scoring: mae
slurm_id: 441225
ylog: 'true'

commit_hash: "088a97b"
date: "Mon Oct 30 16:34:55 UTC 2023"
