cutoff: 20
job_name: job_2023-10-12_query-1600_v000
n_iterations: 20
n_projections: 50
n_query: 1600
nu: 1.5
reason: 1600 queries
scoring: mae
slurm_id: 475492
ylog: 0

commit_hash: "394e579"
date: "Sun Jul  7 23:44:38 UTC 2024"
