cutoff: 20
job_name: job_2023-10-12_query-1600_v000
n_iterations: 20
n_projections: 50
n_query: 1600
nu: 1.5
reason: 1600 queries
scoring: mae
slurm_id: 448354
ylog: 0

commit_hash: "81d1240"
date: "Wed Dec  6 15:50:41 UTC 2023"
