cutoff: 20
job_name: job_2023-10-12_query-1600_v000
n_iterations: 20
n_projections: 50
n_query: 1600
nu: 1.5
reason: 1600 queries
scoring: mae
slurm_id: 448916
ylog: 0

commit_hash: "c426fea"
date: "Tue Dec 19 22:29:07 UTC 2023"
