cutoff: 20
job_name: job_2023-10-12_query-1600_v000
n_iterations: 20
n_projections: 50
n_query: 1600
nu: 1.5
reason: 1600 queries
scoring: mae
slurm_id: 457800
ylog: 0

commit_hash: "93394ad"
date: "Mon Jan  8 17:00:39 UTC 2024"
