cutoff: 20
job_name: job_2023-10-12_query-1600_v000
n_iterations: 20
n_query: 1600
nu: 1.5
reason: 800 queries
scoring: mae
slurm_id: 439259
ylog: 'true'

commit_hash: "b1615fd"
date: "Mon Oct 23 19:38:21 UTC 2023"
