cutoff: 20
job_name: job_2023-10-12_query-1600_v000
n_iterations: 20
n_projections: 50
n_query: 1600
nu: 1.5
reason: 1600 queries
scoring: mae
slurm_id: 448335
ylog: 0

commit_hash: "5256f05"
date: "Tue Dec  5 20:38:04 UTC 2023"
