cutoff: 20
job_name: job_2023-10-12_query-1600_v000
n_iterations: 20
n_projections: 50
n_query: 1600
nu: 1.5
reason: 1600 queries
scoring: mae
slurm_id: 441806
ylog: 0

commit_hash: "dd83737"
date: "Wed Nov  8 16:29:47 UTC 2023"
