# run with `snakemake --cores 1`

from pathlib import Path

n_micro_samples = 500
n_random_samples = 5
scoring = "mse"
iterations = 50
gen_dir = "data-gen"

work_dir = lambda x: str( Path(f"data-{n_random_samples}-{scoring}-{iterations}-{n_micro_samples}") / x )
work_dir_gen = lambda x: str( Path(f"{gen_dir}") / x )


rule all:
    input:
        work_dir(f"data-pca.npz")

rule ipynb:
    input:
        "{notebook}.md"
    output:
        "{notebook}.ipynb"
    shell:
        "jupytext {input} --to ipynb"

rule data_gen:
    input:
        nb="generate-data.ipynb"
    output:
        nb=work_dir_gen("generate-data.ipynb"),
        da=work_dir_gen(f"data-{n_micro_samples}.npz")
    params:
        n_samples=n_micro_samples,
        dir_=gen_dir
    shell:
        "papermill {input.nb} {output.nb} -p output_file {output.da} -p n_samples {params.n_samples}"


rule pca:
    input:
        da="data/data-500-51-51.npz",
#        da=work_dir_gen(f"data-{n_micro_samples}.npz"),
        nb="pca-analysis.ipynb"
    output:
        nb=work_dir("pca-analysis.ipynb"),
        da=work_dir("data-pca.npz")
    shell:
        "papermill {input.nb} {output.nb} -p input_file {input.da} -p output_file {output.da}"
