n_iterations: 20
# 'mse' or 'r2'
scoring: 'r2'
n_query: 400
job_name: "job_2023-09-05_r2_nu-0_5_v000"
reason: "Run with nu of 0.5"
cutoff: 25
nu: 0.5
ylog: false
commit_hash: "ef35d76"
date: "Tue Sep  5 11:41:55 EDT 2023"
