cutoff: 25
job_name: job_2023-09-12_id-429119_nu-1_2_r2_cutoff-25_v001
n_iterations: 20
n_query: 400
nu: 1.2
reason: run with nu=1.2
scoring: r2
ylog: false

commit_hash: "2a88c9d"
date: "Tue Sep 12 19:36:24 UTC 2023"
