cutoff: 20
job_name: job_2023-10-04_full-no-represent_v000
n_iterations: 20
n_pca_wass: null
n_query: 400
nu: 1.5
reason: Full run without Wasserstein calculation which is too expensive
scoring: mae
slurm_id: 438635
ylog: 'true'

commit_hash: "b96325e"
date: "Tue Oct 10 14:03:10 UTC 2023"
